### ISSUE TITLE
Enhancement: allow a restricted alphabet for regex output

### ISSUE THREAD

**Issue by Zac-HD** [maximkulkin/hypothesis-regex#1]
This would just be passed through to the `characters` and `text` calls.  However you'd also have some annoying validation overhead to give sensible error messages, if you don't want to fail with incomprehensible health-check errors.

You would also need to decide and document whether the alphabet applies to all output (including literals and groups), or only wildcards.  Personally I'd go with the only-wildcards option, as this is much easier to validate - but it then requires clear documentation that the alphabet argument does not wholly restrict output.

**Comment by maximkulkin** [comment]
Well, thing is that if you want to use only particular characters in some places, you specify it as ranges in regex. The exception here is character classes which can mean different things depending on whether unicode is enabled or not. So, my plan is to detect if unicode is/should be enabled and use appropriate configuration for generator strategies.

So, how to detect if unicode should be enabled? I see 3 ways:

1. Add a second argument which would be [regex flags](https://docs.python.org/2/library/re.html#re.DEBUG).
2. If you pass compiled regex instead of string, flags can be derived from it.
3. Lastly, you can use [`(?iLmsux)`](https://docs.python.org/2/library/re.html#regular-expression-syntax) to control flags right from inside pattern string.

Flags include support for [IGNORECASE](https://docs.python.org/2/library/re.html#re.IGNORECASE), [LOCALE](https://docs.python.org/2/library/re.html#re.LOCALE), [MULTILINE](https://docs.python.org/2/library/re.html#re.MULTILINE), [DOTALL](https://docs.python.org/2/library/re.html#re.DOTALL) and [UNICODE](https://docs.python.org/2/library/re.html#re.UNICODE).

@Zac-HD That covers support for unicode in a more elegant way than passing keywords arguments to `characters` or `texts` strategies. If you have any concerns to that, please

**Comment by Zac-HD** [comment]
Yep, that sounds like a better way to do it.  I'd avoid the extra argument as less elegant than deriving flags from the regex itself.

Options two and three are both nicely elegant.  Ideally you could handle both, but equally important is to provide clear errors on things that you *don't* handle, especially to avoid incorrect output.  For example, the [new `(?imsx-imsx:...)` group in Python 3.6](https://docs.python.org/3.6/library/re.html#regular-expression-syntax) would be nice to include, OK to leave out, and bad to get wrong.  (I think the existing error is probably sufficient and correct behaviour, but worth checking)

**Comment by maximkulkin** [comment]
Oh, thank you for pointing that out. I will definitely try to implement support for separate settings for a subsection of regex in corresponding Python versions.

**Comment by maximkulkin** [comment]
That being said, I will close this issue and recreate it with proper title and summary of proposed changes we came so far.

**Comment by maximkulkin** [comment]
Created #3 to track support for regex flags.
