### ISSUE TITLE
Implement support for regex flags

### ISSUE THREAD

**Issue by maximkulkin** [maximkulkin/hypothesis-regex#3]
Regular expression can have flags that alter matching behavior. E.g. IGNORECASE, LOCALE, MULTILINE, DOTALL, UNICODE (Python 2.x) / ASCII-ONLY (Python 3.x).

Strategy should only specifying/detect presence of flags and alter how generators are configured.

Ways to detect regex flags:
1. Add second argument - regex flags - to strategy function. Defaults to None.
2. If regex is a compiled regex (not a string) and flags argument is None, derive flags from compiled regex object.
3. If regex uses `(?aiLmsux)` (and/or `(?imsx-imsx:...)` for Python 3.6) special groups, derive flags for entire pattern or its parts based on those groups.
4. Default values based on Python version (2.x/3.x): unicode support should be disabled by default in Python 2.x and enabled in Python 3.x.

**Comment by Zac-HD** [comment]
Re (1), I've found that interacting arguments are a real pain in the behind (especially when you have to change them in a backwards-compatible way).  I would therefore avoid adding this argument, especially because it's easy to compile the pattern with whatever flags are desired inline.

(2) and (3) look good, so no further comments there.

Re (4), Hypothesis prefers to push the text-is-unicode line (via, eg, our `text()` strategy) - I'd default to unicode for all Python versions.  This also makes the default behaviour of a user's test suite consistent across versions, where every test would have to explicitly specify otherwise.

**Comment by maximkulkin** [comment]
Re you comment on (4), in Python 2.x default is non-unicode. So, here is example
```python
import re
r1 = re.compile('\w+')
r1.match('hello')
# => <_sre.SRE_Match object at 0x000000000>
r1.match('привет')  # doesn't match unicode text by default
# => None
r2 = re.compile('\w+', re.UNICODE)
r2.match('привет')
# => <_sre.SRE_Match object at 0x000000000>
```
The ultimate goal is to generate string that can be matched by given regular expression, so this is definitely something to consider.

Also, when you have a static text in regular expression "abc", if `re.IGNORECASE` flag is specified, it is not sufficient to just produce "abc", the generator should produce strings like "ABC", "Abc", "AbC", etc. This could unveil subtle errors for users who specify IGNORECASE, but expect static text to always be "abc".

**Comment by Zac-HD** [comment]
Of course the output should always be matched by the pattern - I meant that it should output `u'hello'` under Py2, not `u'привет'` (which it might under Py3).  Sorry if that was unclear.

I agree on the possibility of surprising people with IGNORECASE, but don't see the relevance here - did you mean to reply to #5?  I'd just note that literals aren't literal when case is ignored, and hope for the sake of the implementation that the sre_parse handles that for you because it will be annoying otherwise!
